### PR TITLE
Updating numerical parameters

### PR DESCRIPTION
**Pull request by adimako**
@nerisaurus @cekees @tridelat @Giovanni-Cozzuto-1989 

All, I am proposing these new numerical parameters. The reason I am doing this is because we had used this configuration in the first numerical tanks, and these were reported to give good results. I have reasons to believe that the set we currently use is not as good, mainly because I repeated some of the old tests with the parameters in Neri's branch

We had long discussions with @tridelat about the performance of the model under these parameters and how we can get the best out of them. 

One possible way to do is to minimise inputs if possible by grouping parameters that can take a single value, such as the eps. Another way to do it is once we set-up regression tests, we keep changing them one at the time and then review the regression reports to decide.

Sorry I forgot to mention it during the meeting. Looking forward for your opinion

### CODE REVIEW

**Comment by nerisaurus** [comment]
@adimako What's the scope of the usefulness of these parameters? Specifically the linear waves case, or do you think the general idea (tighter shock capturings and beta's, larger eps values, etc.) is a good fit for the other numerical tanks or even similar (dambreak, hydraulic structures...) problems?

**Comment by adimako** [comment]
I believe they are good (but I do not know if they are the best) for the numerical wave tanks. We have come up with slightly different ones for e.g. the sloshing case. @cekees I think it will help if @nerisaurus has the report, so he can have access to the numerical parameters we used before. My opinion is that at least for the test cases we have tried, we should use the ones that know they work.

**Comment by cekees** [comment]
That sounds good. I'll get him a copy if you don't beat me to it.  I'm trying to get some PR's up this morning and start some runs on the HPC, but I will go over your new parameter values before tomorrow.

**Comment by nerisaurus** [comment]
I've got the report now, and it looks very useful.  I'll make a pass through the numerical tanks and other updated code with it (setting parameters to known cases, testing new results, updating some of the documentation) this afternoon or tomorrow (whenever I get finished with the tanks-with-obstacles workflow).

**Comment by cekees** [comment]
These parameters look reasonable to me. I usually err  on the side of large numerical diffusion/viscosity, but if  the model is robust and the results are accurate with these lower  values, then that's great, since it should be more accurate.

**Pull request merged**
